In [325]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

from sklearn.preprocessing import LabelEncoder, OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.metrics import mean_squared_error, r2_score

In [326]:
df1=pd.read_csv("bigmart_train.csv")
df2=pd.read_csv("bigmart_test.csv")

In [327]:
df1.head()

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0           FDA15         9.30          Low Fat         0.016047   
1           DRC01         5.92          Regular         0.019278   
2           FDN15        17.50          Low Fat         0.016760   
3           FDX07        19.20          Regular         0.000000   
4           NCD19         8.93          Low Fat         0.000000   

               Item_Type  Item_MRP Outlet_Identifier  \
0                  Dairy  249.8092            OUT049   
1            Soft Drinks   48.2692            OUT018   
2                   Meat  141.6180            OUT049   
3  Fruits and Vegetables  182.0950            OUT010   
4              Household   53.8614            OUT013   

   Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                       1999      Medium               Tier 1   
1                       2009      Medium               Tier 3   
2                       1999      Medium               Tier 1   
3                       1998         NaN               Tier 3   
4                       1987        High               Tier 3   

         Outlet_Type  Item_Outlet_Sales  
0  Supermarket Type1          3735.1380  
1  Supermarket Type2           443.4228  
2  Supermarket Type1          2097.2700  
3      Grocery Store           732.3800  
4  Supermarket Type1           994.7052

In [328]:
print(df1.shape)
print(df1.columns)

(8523, 12)
Index(['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility',
       'Item_Type', 'Item_MRP', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type', 'Item_Outlet_Sales'],
      dtype='object')


In [329]:
del df1['Item_Identifier']
del df1['Outlet_Identifier']
del df1['Item_Type']
df1.columns

Index(['Item_Weight', 'Item_Fat_Content', 'Item_Visibility', 'Item_MRP',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type', 'Item_Outlet_Sales'],
      dtype='object')

In [330]:
df1.isnull().sum()

Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_MRP                        0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [331]:
from sklearn.preprocessing import LabelEncoder
ifcle = LabelEncoder()
osle = LabelEncoder()
oltle = LabelEncoder()
df1['Item_Fat_Content'] = osle.fit_transform(df1['Item_Fat_Content'])
df1['Outlet_Size'] = osle.fit_transform(df1['Outlet_Size'])
df1['Outlet_Location_Type'] = osle.fit_transform(df1['Outlet_Location_Type'])

df2['Item_Fat_Content'] = osle.fit_transform(df2['Item_Fat_Content'])
df2['Outlet_Size'] = osle.fit_transform(df2['Outlet_Size'])
df2['Outlet_Location_Type'] = osle.fit_transform(df2['Outlet_Location_Type'])

In [332]:
df1["Item_Weight"].fillna(0, inplace = True) 
df1["Outlet_Size"].fillna(0, inplace = True) 

In [333]:
df1.isnull().sum()

Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_MRP                     0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
dtype: int64

In [334]:
del df2['Item_Identifier']
del df2['Outlet_Identifier']
del df2['Item_Type']
df2.columns

Index(['Item_Weight', 'Item_Fat_Content', 'Item_Visibility', 'Item_MRP',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type'],
      dtype='object')

In [335]:
df2.isnull().sum()

Item_Weight                  976
Item_Fat_Content               0
Item_Visibility                0
Item_MRP                       0
Outlet_Establishment_Year      0
Outlet_Size                    0
Outlet_Location_Type           0
Outlet_Type                    0
dtype: int64

In [336]:
df2["Item_Weight"].fillna(0, inplace = True) 
df2["Outlet_Size"].fillna(0, inplace = True) 

In [337]:
df2.isnull().sum()

Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_MRP                     0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
dtype: int64

In [338]:
df1['Item_Fat_Content'].unique()

array([1, 2, 3, 0, 4])

In [339]:
df2['Item_Fat_Content'].unique()

array([1, 4, 2, 0, 3])

In [340]:
df1["Item_Fat_Content"]=df1["Item_Fat_Content"].replace("reg", "Regular")
df1["Item_Fat_Content"]=df1["Item_Fat_Content"].replace(["LF","low fat"], "Low Fat")

In [341]:
df2["Item_Fat_Content"]=df2["Item_Fat_Content"].replace("reg", "Regular")
df2["Item_Fat_Content"]=df2["Item_Fat_Content"].replace(["LF","low fat"], "Low Fat")

In [342]:
df1['Item_Fat_Content'].unique()

array([1, 2, 3, 0, 4])

In [343]:
df2['Item_Fat_Content'].unique()

array([1, 4, 2, 0, 3])

In [344]:
df1.head()

Item_Weight  Item_Fat_Content  Item_Visibility  Item_MRP  \
0         9.30                 1         0.016047  249.8092   
1         5.92                 2         0.019278   48.2692   
2        17.50                 1         0.016760  141.6180   
3        19.20                 2         0.000000  182.0950   
4         8.93                 1         0.000000   53.8614   

   Outlet_Establishment_Year  Outlet_Size  Outlet_Location_Type  \
0                       1999            1                     0   
1                       2009            1                     2   
2                       1999            1                     0   
3                       1998            3                     2   
4                       1987            0                     2   

         Outlet_Type  Item_Outlet_Sales  
0  Supermarket Type1          3735.1380  
1  Supermarket Type2           443.4228  
2  Supermarket Type1          2097.2700  
3      Grocery Store           732.3800  
4  Supermarket Type1           994.7052

In [345]:
dummy1 = pd.get_dummies(df1['Outlet_Type'])
dummy2 = pd.get_dummies(df2['Outlet_Type'])

In [346]:
new_df1 = pd.concat([df1, dummy1], axis = 1)
new_df1.head()

Item_Weight  Item_Fat_Content  Item_Visibility  Item_MRP  \
0         9.30                 1         0.016047  249.8092   
1         5.92                 2         0.019278   48.2692   
2        17.50                 1         0.016760  141.6180   
3        19.20                 2         0.000000  182.0950   
4         8.93                 1         0.000000   53.8614   

   Outlet_Establishment_Year  Outlet_Size  Outlet_Location_Type  \
0                       1999            1                     0   
1                       2009            1                     2   
2                       1999            1                     0   
3                       1998            3                     2   
4                       1987            0                     2   

         Outlet_Type  Item_Outlet_Sales  Grocery Store  Supermarket Type1  \
0  Supermarket Type1          3735.1380              0                  1   
1  Supermarket Type2           443.4228              0                  0   
2  Supermarket Type1          2097.2700              0                  1   
3      Grocery Store           732.3800              1                  0   
4  Supermarket Type1           994.7052              0                  1   

   Supermarket Type2  Supermarket Type3  
0                  0                  0  
1                  1                  0  
2                  0                  0  
3                  0                  0  
4                  0                  0

In [347]:
new_df2 = pd.concat([df2, dummy2], axis = 1)
new_df2.head()

Item_Weight  Item_Fat_Content  Item_Visibility  Item_MRP  \
0       20.750                 1         0.007565  107.8622   
1        8.300                 4         0.038428   87.3198   
2       14.600                 1         0.099575  241.7538   
3        7.315                 1         0.015388  155.0340   
4        0.000                 2         0.118599  234.2300   

   Outlet_Establishment_Year  Outlet_Size  Outlet_Location_Type  \
0                       1999            1                     0   
1                       2007            3                     1   
2                       1998            3                     2   
3                       2007            3                     1   
4                       1985            1                     2   

         Outlet_Type  Grocery Store  Supermarket Type1  Supermarket Type2  \
0  Supermarket Type1              0                  1                  0   
1  Supermarket Type1              0                  1                  0   
2      Grocery Store              1                  0                  0   
3  Supermarket Type1              0                  1                  0   
4  Supermarket Type3              0                  0                  0   

   Supermarket Type3  
0                  0  
1                  0  
2                  0  
3                  0  
4                  1

In [348]:
del new_df1['Outlet_Type']
del new_df2['Outlet_Type']

In [349]:
new_df1.head()

Item_Weight  Item_Fat_Content  Item_Visibility  Item_MRP  \
0         9.30                 1         0.016047  249.8092   
1         5.92                 2         0.019278   48.2692   
2        17.50                 1         0.016760  141.6180   
3        19.20                 2         0.000000  182.0950   
4         8.93                 1         0.000000   53.8614   

   Outlet_Establishment_Year  Outlet_Size  Outlet_Location_Type  \
0                       1999            1                     0   
1                       2009            1                     2   
2                       1999            1                     0   
3                       1998            3                     2   
4                       1987            0                     2   

   Item_Outlet_Sales  Grocery Store  Supermarket Type1  Supermarket Type2  \
0          3735.1380              0                  1                  0   
1           443.4228              0                  0                  1   
2          2097.2700              0                  1                  0   
3           732.3800              1                  0                  0   
4           994.7052              0                  1                  0   

   Supermarket Type3  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0

In [350]:
new_df2.head()

Item_Weight  Item_Fat_Content  Item_Visibility  Item_MRP  \
0       20.750                 1         0.007565  107.8622   
1        8.300                 4         0.038428   87.3198   
2       14.600                 1         0.099575  241.7538   
3        7.315                 1         0.015388  155.0340   
4        0.000                 2         0.118599  234.2300   

   Outlet_Establishment_Year  Outlet_Size  Outlet_Location_Type  \
0                       1999            1                     0   
1                       2007            3                     1   
2                       1998            3                     2   
3                       2007            3                     1   
4                       1985            1                     2   

   Grocery Store  Supermarket Type1  Supermarket Type2  Supermarket Type3  
0              0                  1                  0                  0  
1              0                  1                  0                  0  
2              1                  0                  0                  0  
3              0                  1                  0                  0  
4              0                  0                  0                  1

In [351]:
features = new_df1.drop(['Item_Outlet_Sales'], axis = 1)
target = new_df1[['Item_Outlet_Sales']]

X_train, X_test, y_train, y_test = train_test_split(features, target, train_size = 0.85, random_state = 5)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(7244, 11)
(1279, 11)
(7244, 1)
(1279, 1)


In [352]:
my_model = LinearRegression()

my_model.fit(X_train, y_train)

predictions = my_model.predict(X_test)
predictions_train = my_model.predict(X_train)

print('MSE: ',mean_squared_error(predictions,y_test))

print('RMSE: ', np.sqrt(mean_squared_error(predictions,y_test)))

print('r2_score on test data : ', r2_score(predictions,y_test))
print('r2_score on train data : ', r2_score(predictions_train,y_train))

MSE:  1284757.7308120164
RMSE:  1133.4715394803773
r2_score on test data :  0.22242811822892694
r2_score on train data :  0.22939315977560915
